version: '3.8'

services:
  app:
    image: ltreze/app:latest
    container_name: app_container
    restart: always
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 10s npm start
    ports:
      - "3008:3008"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_DATABASE=mydatabase
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    depends_on:
      - app

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
